name: CI Build and publish WebSocket-Server
on:
  push:
    paths:
      - 'node-websocket-server/**'        
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3    
      - 
        name: Build and publish "latest" Docker image
        uses: VaultVulp/gp-docker-action@1.6.0
        with:          
          github-token: '${{ secrets.PACKAGE_TOKEN }}'
          image-name: rover.socket-server
          build-context: ./node-websocket-server
